\ir permissions.sql
\ir marketing_sources.sql
\ir owners.sql
\ir repos.sql
\ir apps.sql
\ir teams.sql
\ir services.sql
\ir builds.sql
\ir releases.sql
\ir tokens.sql
\ir subscriptions.sql
\ir beta_users.sql
\ir external_service_metadata.sql
